name: "🐛 Bug Report"
description: "Report a bug to help us improve the Code With Mahesh project"
title: "🐛 Bug Report: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report form! 🙏  
        Your feedback helps us make the project better for everyone.
  - type: textarea
    id: steps-to-reproduce
    validations:
      required: true
    attributes:
      label: "👟 Reproduction steps"
      description: "How do you trigger this bug? Please describe the steps to reproduce it."
      placeholder: "When I ..."
  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: "👍 Expected behavior"
      description: "What did you expect to happen?"
      placeholder: "It should ..."
  - type: textarea
    id: actual-behavior
    validations:
      required: true
    attributes:
      label: "👎 Actual Behavior"
      description: "What actually happened? Feel free to include screenshots if relevant."
      placeholder: "It actually ..."
  - type: dropdown
    id: operating-system
    attributes:
      label: "💻 Operating system"
      description: "What OS is your device/server running?"
      options:
        - Linux
        - MacOS
        - Windows
        - Something else
    validations:
      required: true
  - type: textarea
    id: environment
    validations:
      required: true
    attributes:
      label: "🧱 Your Environment"
      description: "Which version of tools are you using? (e.g., HTML5/Web/Browser)"
      placeholder: "I use ..."
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "👀 Have you checked if this issue already exists?"
      description: "Have you searched for a similar issue or checked our previous reports?"
      options:
        - label: "I checked and didn't find a similar issue"
          required: true
  - type: checkboxes
    id: read-code-of-conduct
    attributes:
      label: "🏢 Have you read the Code of Conduct?"
      options:
        - label: "I have read the [Code of Conduct](https://github.com/CodeWithMahesh-com/.github/blob/main/CODE_OF_CONDUCT.md)"
          required: true
